name: flutter_base_workspace

packages:
  - apps/*
  - packages/*

command:
  bootstrap:
    # Tüm paketler için pub get çalıştırılsın
    runPubGetInParallel: false
    
scripts:
  analyze:
    run: |
      melos exec -c 1 -- \
        dart analyze .
    description: "Tüm paketlerde analiz çalıştırır."

  format:
    run: |
      melos exec -c 1 -- \
        dart format .
    description: "Tüm paketleri formatlar."

  test:select:
    run: |
      melos exec -c 1 --dir-exists="test" -- \
        flutter test
    description: "Testleri çalıştırır (sadece test klasörü olan paketlerde)."

  gen:build:
    run: |
      melos exec -c 1 --depends-on="build_runner" -- \
        dart run build_runner build --delete-conflicting-outputs
    description: "build_runner kullanan paketlerde kod üretimi yapar."

  clean:
    run: |
      melos exec -- \
        flutter clean
    description: "Tüm paketleri temizler."
    
  postbootstrap:
    run: dart pub global activate flutter_gen
    description: "Global araçları kurar."
