#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Users/engin/fvm/versions/3.47.1"
export "FLUTTER_APPLICATION_PATH=/Users/engin/Documents/{{name.titleCase()}}/{{name.snakeCase()}}/apps/client"
export "FLUTTER_FRAMEWORK_SWIFT_PACKAGE_PATH=/Users/engin/Documents/{{name.titleCase()}}/{{name.snakeCase()}}/apps/client/ios/Flutter/ephemeral/Packages/.packages/FlutterFramework"
export "COCOAPODS_PARALLEL_CODE_SIGN=true"
export "FLUTTER_TARGET=/var/folders/yf/sgm3ychx09zc3q8xzybg2n4r0000gp/T/flutter_tools.UOsPZf/flutter_test_listener.YmiiCO/listener.dart"
export "FLUTTER_BUILD_DIR=build"
export "FLUTTER_BUILD_NAME=0.1.0"
export "FLUTTER_BUILD_NUMBER=0.1.0"
export "DART_DEFINES=RkxVVFRFUl9BUFBfRkxBVk9SPWRldg==,RkxVVFRFUl9CVUlMRF9OQU1FPTAuMS4w,RkxVVFRFUl9WRVJTSU9OPTMuNDcuMQ==,RkxVVFRFUl9DSEFOTkVMPXN0YWJsZQ==,RkxVVFRFUl9HSVRfVVJMPWh0dHBzOi8vZ2l0aHViLmNvbS9mbHV0dGVyL2ZsdXR0ZXIuZ2l0,RkxVVFRFUl9GUkFNRVdPUktfUkVWSVNJT049NjY1NTQ4MmVjMA==,RkxVVFRFUl9FTkdJTkVfUkVWSVNJT049NWQ1MzE3ODg2OQ==,RkxVVFRFUl9EQVJUX1ZFUlNJT049My4xMy4x,SU5URUdSQVRJT05fVEVTVF9TSE9VTERfUkVQT1JUX1JFU1VMVFNfVE9fTkFUSVZFPWZhbHNl"
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=true"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=/Users/engin/Documents/{{name.titleCase()}}/{{name.snakeCase()}}/apps/client/.dart_tool/package_config.json"
export "FLAVOR=dev"
