targets:
  $default:
    builders:
      slang_build_runner:
        options:
          base_locale: en
          input_directory: lib
          input_file_pattern: .i18n.json
          output_directory: lib/core/translations
          output_file_name: strings.g.dart
          namespaces: true
          translate_var: t
          enum_name: AppLocale
