name: example
description: Exemplifies usage of {{name.snakeCase()}}_core
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.13.1
  flutter: ">=3.47.1"

dependencies:
  flutter:
    sdk: flutter
  {{name.snakeCase()}}_core:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
