name: flutter_base_core
description: Core shared infrastructure for Flutter Base project.
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ^3.6.0
  flutter: ">=3.16.0"

dependencies:
  dio: ^5.4.0
  dio_smart_retry: ^6.0.0
  equatable: ^2.0.5
  firebase_analytics: ^12.1.0
  firebase_core: ^4.3.0
  firebase_crashlytics: ^5.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  injectable: ^2.3.2
  json_annotation: ^4.8.1
  logger: ^2.0.0

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.8
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  injectable_generator: ^2.5.3
  json_serializable: ^6.7.1
  mocktail: ^1.0.4
