name: flutter_base_core
description: A robust, opinionated core infrastructure for Flutter apps. Includes network (Dio), storage, and logging utilities designed for Feature-First Clean Architecture.
version: 0.1.0
homepage: https://github.com/yagmure15/flutter_base
repository: https://github.com/yagmure15/flutter_base

environment:
  sdk: ^3.6.0
  flutter: ">=3.16.0"

dependencies:
  connectivity_plus: ^6.0.3
  dio: ^5.4.0
  dio_smart_retry: ^6.0.0
  equatable: ^2.0.5
  firebase_analytics: ^12.1.0
  firebase_core: ^4.3.0
  firebase_crashlytics: ^5.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  formz: ^0.7.0
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  injectable: ^2.3.2
  json_annotation: ^4.8.1
  logger: ^2.0.0
  permission_handler: ^11.3.0
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.2.2

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.8
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  injectable_generator: ^2.5.3
  json_serializable: ^6.7.1
  mocktail: ^1.0.4
