name: example
description: Exemplifies usage of flutter_base_core
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_base_core:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
